### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by danvelcab** [jublonet/codebird-js#146]
Hi. I'm using codebird-js with pavelk2/social-feed and I get this error:

Failed to load https://api.jublo.net/codebird/oauth2/token: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://my-domain.es' is therefore not allowed access. The response had HTTP status code 502.

Can anybody help me?
Thanks

**Comment by svoltmer** [comment]
I receive the same error after the oauth2/token returns a 502 error.

Failed to load https://api.jublo.net/codebird/oauth2/token: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.rose-hulman.edu' is therefore not allowed access. The response had HTTP status code 502.

It was working yesterday, but for weeks it's taken at least a minute to validate the token and populate the feed. I haven't changed anything on my end.

**Comment by svoltmer** [comment]
Now I am receiving this error:

Failed to load https://api.jublo.net/codebird/1.1/statuses/user_timeline.json?screen_name=RoseHulman&include_rts=true&exclude_replies=true&count=1&tweet_mode=extended: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.rose-hulman.edu' is therefore not allowed access. The response had HTTP status code 502.

**Comment by HarshaVardhanPVK** [comment]
Hi, any one of you got fix of this issue? It used to work fine for me too and suddenly start throwing `No 'Access-Control-Allow-Origin' header is present error` for me too.

**Comment by jublo** [comment]
@HarshaVardhanPVK Hi there, what environment are you using – a browser?

**Comment by HarshaVardhanPVK** [comment]
Yes @jublo through browser only I am trying to trigger

**Comment by HarshaVardhanPVK** [comment]
@jublo, Do you guys have any fix on this issue?

**Comment by jublo** [comment]
@HarshaVardhanPVK I will take a look at it this week and update you. :)

**Comment by rowangit** [comment]
Same issue today just out of the blue

**Comment by joshuaatkins** [comment]
Hi all, this should now have been resolved. Let me know if you have any further issues.

**Comment by dubeyjags** [comment]
Access to XMLHttpRequest at 'https://api.jublo.net/codebird/oauth2/token' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Not Solved. please help me

**Comment by thomas-white-ucf** [comment]
running into these issues as well @dubeyjags
